name: binder-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - matplotlib
  # pip 자체를 하나의 항목으로 추가
  - pip
  # pip 아래에 설치할 패키지 리스트
  - pip:
    - some-other-package
